name: notas_corte_flutter
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  scoped_model: ^1.0.1
  http: ^0.12.0+1
  flutter_html: ^0.9.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  fonts:
    - family: RobotoMono
      fonts:
        - asset: assets/fonts/RobotoMono-Bold.ttf
        - asset: assets/fonts/RobotoMono-Italic.ttf
        - asset: assets/fonts/RobotoMono-Regular.ttf
          weight: 700
    - family: ProductSans
      fonts:
        - asset: assets/fonts/ProductSans-Bold.ttf
        - asset: assets/fonts/ProductSans-Italic.ttf
        - asset: assets/fonts/ProductSans-Regular.ttf
          weight: 700

  uses-material-design: true